export default {
  defaultConfig: {
    name: 'Wemo',
    mode: 'auto',
    hideConnectionErrors: false,
    disablePlugin: false,
    discoveryInterval: 30,
    pollingInterval: 30,
    upnpInterval: 300,
    disableUPNP: false,
    disableDeviceLogging: false,
    removeByName: '',
    wemoClient: {
      callback_url: '',
      listen_interface: '',
      port: 0,
      discover_opts: {
        interfaces: '',
        explicitSocketBind: true,
      },
    },
    makerTypes: [],
    wemoInsights: [],
    wemoLights: [],
    wemoLinks: [],
    wemoMotions: [],
    wemoOthers: [],
    wemoOutlets: [],
    platform: 'Wemo',
  },

  defaultValues: {
    adaptiveLightingShift: 0,
    brightnessStep: 1,
    discoveryInterval: 30,
    makerTimer: 20,
    noMotionTimer: 60,
    pollingInterval: 30,
    port: 0,
    showAs: 'default',
    timeDiff: 1,
    transitionTime: 0,
    upnpInterval: 300,
    wattDiff: 1,
  },

  minValues: {
    adaptiveLightingShift: -1,
    discoveryInterval: 15,
    brightnessStep: 1,
    makerTimer: 1,
    noMotionTimer: 0,
    pollingInterval: 15,
    port: 0,
    timeDiff: 1,
    transitionTime: 0,
    upnpInterval: 60,
    wattDiff: 1,
  },

  allowed: {
    mode: ['auto', 'semi', 'manual'],
    makerTypes: [
      'label',
      'serialNumber',
      'ignoreDevice',
      'makerType',
      'makerTimer',
      'reversePolarity',
      'manualIP',
      'listenerType',
    ],
    wemoInsights: [
      'label',
      'serialNumber',
      'ignoreDevice',
      'showTodayTC',
      'wattDiff',
      'timeDiff',
      'showAs',
      'outletInUseTrue',
      'manualIP',
      'listenerType',
    ],
    wemoLights: [
      'label',
      'serialNumber',
      'ignoreDevice',
      'enableColourControl',
      'adaptiveLightingShift',
      'brightnessStep',
      'transitionTime',
      'manualIP',
      'listenerType',
    ],
    wemoLinks: ['label', 'serialNumber', 'ignoreDevice', 'manualIP', 'listenerType'],
    wemoMotions: [
      'label',
      'serialNumber',
      'ignoreDevice',
      'noMotionTimer',
      'manualIP',
    ],
    wemoOthers: [
      'label',
      'serialNumber',
      'ignoreDevice',
      'manualIP',
      'listenerType',
    ],
    wemoOutlets: [
      'label',
      'serialNumber',
      'ignoreDevice',
      'showAs',
      'manualIP',
      'listenerType',
    ],
    listenerType: ['default', 'http'],
    showAs: ['default', 'switch', 'purifier'],
  },

  portsToScan: [49153, 49152, 49154, 49155, 49151, 49156, 49157, 49158, 49159],
  servicesToSubscribe: [
    'urn:Belkin:service:basicevent:1',
    'urn:Belkin:service:insight:1',
    'urn:Belkin:service:bridge:1',
  ],
};
