on:
  issues:
    types:
      - labeled
      - unlabeled

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Label Commenter
        uses: peaceiris/actions-label-commenter@v1
        with:
          config_file: .github/label-commenter-config.yml
